//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvioDocumento
    {
        public int IdEnvio { get; set; }
        public string TipoDocumento { get; set; }
        public int IdUsuario { get; set; }
        public int IdDeptOrigen { get; set; }
        public int IdDeptDestino { get; set; }
        public string Secuencia { get; set; }
        public DateTime Fecha { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Departamentos Departamentos1 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
