//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using CapaEntidades;
    
    public partial class ProyectoFinalP2Entities : DbContext
    {
        public ProyectoFinalP2Entities()
            : base("name=ProyectoFinalP2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<EnvioDocumento> EnvioDocumento { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual ObjectResult<ReporteDepartamentos_Result> ReporteDepartamentos(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReporteDepartamentos_Result>("ReporteDepartamentos", nombreParameter);
        }
    
        public virtual ObjectResult<ReporteDocFecha_Result> ReporteDocFecha(string desde, string hasta)
        {
            var desdeParameter = desde != null ?
                new ObjectParameter("desde", desde) :
                new ObjectParameter("desde", typeof(string));
    
            var hastaParameter = hasta != null ?
                new ObjectParameter("hasta", hasta) :
                new ObjectParameter("hasta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReporteDocFecha_Result>("ReporteDocFecha", desdeParameter, hastaParameter);
        }
    
        public virtual ObjectResult<ReporteDocumentos_Result> ReporteDocumentos(string filtro, string consulta)
        {
            var filtroParameter = filtro != null ?
                new ObjectParameter("Filtro", filtro) :
                new ObjectParameter("Filtro", typeof(string));
    
            var consultaParameter = consulta != null ?
                new ObjectParameter("Consulta", consulta) :
                new ObjectParameter("Consulta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReporteDocumentos_Result>("ReporteDocumentos", filtroParameter, consultaParameter);
        }
    
        public virtual ObjectResult<ReporteUsuarios_Result> ReporteUsuarios(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReporteUsuarios_Result>("ReporteUsuarios", nombreParameter);
        }
    }
}
